name: Deploy TurnoAgua to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build
      # Usamos el comando para generar los archivos de producción
      run: npx ng build --configuration production --base-href /turnosagua/

    - name: Fix for GitHub Pages 404
      # Esto ayuda a que las rutas de Angular funcionen si refrescas la página
      run: cp dist/turnoagua/browser/index.html dist/turnoagua/browser/404.html

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        # IMPORTANTE: Verifica que esta ruta exista en tu dist local
        folder: dist/turnoagua/browser 
        branch: gh-pages